# Generated by Django 4.2.6 on 2023-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
                ('habit_datetime', models.DateTimeField(verbose_name='Дата выполнения')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('pleasant_sign', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('frequency', models.IntegerField(blank=True, default=1, null=True, verbose_name='Интервал (дней)')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.IntegerField(verbose_name='Время на выполнение')),
                ('public_sign', models.BooleanField(blank=True, default=False, null=True, verbose_name='Публичный')),
                ('launched', models.BooleanField(blank=True, default=False, null=True, verbose_name='Задание выполняется')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
